apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "radars.fullname" . }}-kpi
  labels:
    {{- include "radars.labels" . | nindent 4 }}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kpi
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
