apiVersion: v1
kind: Service
metadata:
  name: {{ include "radars.fullname" . }}-front
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
  selector:
    {{- include "radars.selectorLabels" . | nindent 4 }}
    component: front
