# Default values for radars.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

front:
  replicaCount: 1
  image:
    repository: loicag/radars-front
    tag: latest
    pullPolicy: Always

back:
  replicaCount: 1
  image:
    repository: loicag/radars-back
    tag: latest
    pullPolicy: Always
  database:
    host: radars-mariadb
    name: radars
    user: root
    password: root

etl:
  image:
    repository: loicag/radars-etl
    tag: latest
    pullPolicy: Always
  database:
    host: radars-mariadb
    name: radars
    user: root
    password: root

mariadb:
  auth:
    rootPassword: root #TODO use existingSecret instead
    database: radars
  initdbScripts:
    create_table_sensor.sql: |
      CREATE TABLE sensor(
        id VARCHAR(20),
        address VARCHAR(255),
        latitude DECIMAL(10,7),
        longitude DECIMAL(10,7),
        position POINT NOT NULL,
        speed_limit INT,
        PRIMARY KEY(id),
        SPATIAL INDEX(position)
      );
    create_table_measurement.sql: |
      CREATE TABLE measurement (
        id INT,
        sensor_id VARCHAR(20),
        datetime DATETIME,
        speed INT,
        PRIMARY KEY(id)
      );
    create_table_statistic_hourly.sql: |
      CREATE TABLE statistic_hourly (
        sensor_id VARCHAR(20),
        datetime DATETIME,
        n_total INT,
        n_0_to_30 INT,
        n_30_to_40 INT,
        n_40_to_50 INT,
        n_50_to_60 INT,
        n_60_to_70 INT,
        n_over_70 INT,
        v_avg DOUBLE,
        v_50p DOUBLE,
        v_85p DOUBLE,
        v_max DOUBLE,
        PRIMARY KEY(sensor_id, datetime)
      );
    create_table_statistic_daily.sql: |
      CREATE TABLE statistic_daily (
        sensor_id VARCHAR(20),
        datetime DATETIME,
        n_total INT,
        n_0_to_30 INT,
        n_30_to_40 INT,
        n_40_to_50 INT,
        n_50_to_60 INT,
        n_60_to_70 INT,
        n_over_70 INT,
        v_avg DOUBLE,
        v_50p DOUBLE,
        v_85p DOUBLE,
        v_max DOUBLE,
        PRIMARY KEY(sensor_id, datetime)
      );

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: ClusterIP
  port: 80

ingress:
  className: nginx
  host: radars.loicgombeaud.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      gzip on;
      gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    nginx.org/basic-auth-secret: basic-auth
